# Same as v3 but with an epsilon more high

learning_rate: 1e-4
gamma: 0.95
replay_buffer_size: 10000
replay_buffer_batch_size: 300
step_per_epoch: 100
target_model_update_freq: 10
epsilon_update_freq: 20
epsilon_init: 1.0
epsilon_min: 0.2
epsilon_a: 0.995
epsilon_b: -0.001

