# Increase replay buffer size and decrease batch size

learning_rate: 1e-4
gamma: 0.94
replay_buffer_size: 10000
replay_buffer_batch_size: 200
step_per_epoch: 100
target_model_update_freq: 10
epsilon_update_freq: 10
epsilon_init: 1.0
epsilon_min: 0.02
epsilon_a: 0.99
epsilon_b: -0.01
